### ISSUE TITLE
I can't install the bundle

### ISSUE THREAD

**Issue by YoussefChafai** [kswedberg/jquery-tmbundle#14]
Hi Karl,

I can't get the Bundle installed / working in TextMate.

I don't use GIT.

So I downloaded the zip file (it automatically unzipped; I work on mac and using Safari), and I renamed the folder "JavaScript jQuery.tmbundle" which is showing following content (the unzipped folder is automatically located in my download folder, and I also renamed the folder with my "Download" folder):

Commands folder
info.plist
README.md
Snippets
Support
Syntaxes

So steps 5 and 6 are not working for me:

open TextMate and select the following menu item: Bundles > Bundle Editor > Reload Bundles
show the Bundle Editor (Bundles > Bundle Editor > Show Bundle Editor)

What am I doing wrong?
Could you advise me on this?

Thanks for your support!

Best,
Youssef

**Comment by kswedberg** [comment]
Hi Youssef,

The only thing I can think of at the moment is that you didn't mention double-clicking on the .tmbundle file after you renamed it (step 4). Did you do that?

**Comment by ofi** [comment]
Hi Youssef,

although it may be late after four months it's probably not too late for this hint: In the Bundle editor open the "Filter list..." dialog by clicking on the button at the bottom of the language list and check if "JavaScript jQuery" has got a checkmark, because it hadn't in my case although I installed via git.

Cheers
  [ofi]
